version: "5"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
  customerapi:
    image: johnnysilva1995str/customerapi:latest
    container_name: "customerapi"
    ports:
      - 9090:8080
    links:
      - mongo