version: "5"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
  customerapi:
    image: johnnysilva1995str/customerapi:latest
    container_name: "customerapi"
    ports:
      - "9090:8080"
    links:
      - mongo